C  COMPUTE THE I-TH EQUALITY CONSTAINT, VALUE IS HXI
      SUBROUTINE ESH(I,X,HXI)
      INCLUDE 'O8FUCO.INC'
      INCLUDE 'O8FINT.INC'
      DOUBLE PRECISION X(*),HXI
      INTEGER I
      INTEGER J
      SAVE
      IF ( BLOC ) THEN
        IF ( VALID ) THEN
          IF ( GUNIT(1,I) .NE. 1 ) CRES(I)=CRES(I)+1
          HXI=FU(I)
          RETURN
        ELSE
          STOP 'DONLP2: BLOC-CALL WITH FUNCTONINFORMATION INVALID'
        ENDIF
      ELSE
        DO J=1,N
          XTR(J)=X(J)*XSC(J)
        ENDDO
        CALL EH(I,XTR,HXI)
        RETURN
      ENDIF
      END
