C EXAMPLE WHERE EXTENDED MFCQ DOESN'T HOLD
C NLP ITSELF QUITE REGULAR
C SOLUTION 1/SQRT(2),1/SQRT(2) . WITH TAU0=0.5 THE METHODS FAILS BECAUSE
C AT ZERO THE MOST VIOLATED CONSTRAINT (THE EQUALITY) CANNOT BE REDUCED
C SINCE ITS GRADIENT IS ZERO. WITH TAU0 LARGER THAN ONE THIS WILL NOT
C OCCUR SINCE GRAD(F) TAKES US AWAY FROM ZERO
      SUBROUTINE SETUP
      INCLUDE 'O8COMM.INC'
C   NO SPECIAL USER DATA
      RETURN
      END
      SUBROUTINE SETUP0
      INCLUDE 'O8COMM.INC'
      INTEGER I,J,NUSER
      PARAMETER (NUSER=2)
      DOUBLE PRECISION XST0(NUSER)
      DATA (XST0(I),I=1,NUSER)
     F  /-0.4D0,-0.4D0
     F       /
C   NAME IS IDENT OF THE EXAMPLE/USER AND CAN BE SET AT USERS WILL
C   THE FIRST CHARACTER MUST BE ALPHABETIC.  40 CHARACTERS MAXIMUM
       NAME='NMCFQMHH'
C   X IS INITIAL GUESS AND ALSO HOLDS THE CURRENT SOLUTION
C   PROBLEM DIMENSION N=DIM(X), NH=DIM(H), NG=DIM(G)
      N=NUSER
      NH=1
      NG=2
      ANALYT=.TRUE.
      EPSDIF=1.D-16
      PROU=10
      MEU=20
C   DEL0 AND TAU0: SEE BELOW
      DEL0=0.5D0
      TAU0=0.5D0
      DO I=1,N
        X(I)=XST0(I)
      ENDDO
C    GUNIT-ARRAY, SEE DONLPDOC.TXT
      DO J=0,NH+NG
        GUNIT(1,J)=-1
        GUNIT(2,J)=0
        GUNIT(3,J)=0
      ENDDO
      RETURN
      END

C     OBJECTIVE FUNCTION
      SUBROUTINE EF(X,FX)
      INCLUDE 'O8FUCO.INC'
      DOUBLE PRECISION FX,X(*)
      ICF=ICF+1
      FX=-(X(1)+X(2))
      RETURN
      END
C     GRADIENT OF OBJECTIVE FUNCTION
      SUBROUTINE EGRADF(X,GRADF)
      INCLUDE 'O8FUCO.INC'
      DOUBLE PRECISION X(*),GRADF(*)
      INTEGER J
C     USER DECLARATIONS, IF ANY ,FOLLOW
      ICGF=ICGF+1
      DO           J=1,2
        GRADF(J)=-1.D0
      ENDDO
      RETURN
      END

C  COMPUTE THE I-TH EQUALITY CONSTAINT, VALUE IS HXI
      SUBROUTINE EH(I,X,HXI)
      INCLUDE 'O8FUCO.INC'
      INTEGER I
      DOUBLE PRECISION X(*),HXI
      CRES(I)=CRES(I)+1
      HXI=X(1)**2+X(2)**2-1.D0
      RETURN
      END
C  COMPUTE THE GRADIENT OF THE I-TH EQUALITY CONSTRAINT
      SUBROUTINE EGRADH(I,X,GRADHI)
      INCLUDE 'O8FUCO.INC'
      INTEGER I,J
      DOUBLE PRECISION X(*),GRADHI(*)
      IF ( GUNIT(1,I) .NE. 1 ) CGRES(I)=CGRES(I)+1
      DO  J=1,N
        GRADHI(J)=X(J)*2.D0
      ENDDO
      RETURN
      END

C COMPUTE THE I-TH INEQUALITY CONSTAINT, BOUNDS INCLUDED

      SUBROUTINE EG(I,X,GXI)
      INCLUDE 'O8FUCO.INC'
      INTEGER I
      DOUBLE PRECISION GXI,X(*)
      IF ( GUNIT(1,I+NH) .EQ. -1 ) CRES(I+NH)=CRES(I+NH)+1
      GOTO (100,200), I
  100 CONTINUE
      GXI=X(1)
      RETURN
  200 CONTINUE
      GXI=X(2)
      RETURN
      END
C COMPUTE THE GRADIENT OF THE I-TH INEQUALITY CONSTRAINT
      SUBROUTINE EGRADG(I,X,GRADGI)
      INCLUDE 'O8FUCO.INC'
      INTEGER I
      DOUBLE PRECISION X(*) ,GRADGI(*)
      IF ( GUNIT(1,I+NH) .EQ. -1 ) CGRES(I+NH)=CGRES(I+NH)+1
      GOTO (100,200), I
  100 CONTINUE
      GRADGI(1)=1.D0
      GRADGI(2)=0.D0
      RETURN
  200 CONTINUE
      GRADGI(1)=0.D0
      GRADGI(2)=1.D0
      RETURN
      END
