      SUBROUTINE SETUP
      RETURN
      END
C    MARATOS'S EXAMPLE, SHOWING THE WELL KNOWN EFFECT OF STEPSIZE REDUCTION
C    CHANGE DONLP'S PARAMETER SMALLD IN ORDER TO SEE IT!
      SUBROUTINE EF(X,FX)
      INCLUDE 'O8FUCO.INC'
      DOUBLE PRECISION X(*),FX
      ICF=ICF+1
      FX=-X(1) + 10.D0*(X(1)**2+X(2)**2-1.D0)
      RETURN
      END
      SUBROUTINE EGRADF(X,GRADF)
      INCLUDE 'O8FUCO.INC'
      DOUBLE PRECISION X(*),GRADF(*)
      ICGF=ICGF+1
      GRADF(1)=-1.D0+20.D0*X(1)
      GRADF(2)=20.D0*X(2)
      RETURN
      END
      SUBROUTINE EH(I,X,HXI)
      INCLUDE 'O8FUCO.INC'
      INTEGER I
      DOUBLE PRECISION X(*),HXI
      CRES(I)=CRES(I)+1
      HXI=X(1)**2+X(2)**2-1.D0
      RETURN
      END
      SUBROUTINE EGRADH(I,X,GRADHI)
      INCLUDE 'O8FUCO.INC'
      INTEGER I
      DOUBLE PRECISION X(*),GRADHI(*)
      CGRES(I)=CGRES(I)+1
      GRADHI(1)=2.D0*X(1)
      GRADHI(2)=2.D0*X(2)
      RETURN
      END
      SUBROUTINE EG(I,X,GXI)
      INCLUDE 'O8FUCO.INC'
      INTEGER I
      DOUBLE PRECISION X(*),GXI
      RETURN
      END
      SUBROUTINE EGRADG(I,X,GRADGI)
      INCLUDE 'O8FUCO.INC'
      INTEGER I
      DOUBLE PRECISION X(*) ,GRADGI(*)
      RETURN
      END
      BLOCK DATA
      INCLUDE 'O8BLOC.INC'
      INTEGER I,J
      DATA NAME/'MARATOS0'/
      DATA X(1),X(2)/0.8D0,0.6D0/
      DATA N/2/ , NH/1/ , NG/0/
      DATA DEL0/1.00D-1/ ,TAU0/0.5D0/ ,TAU/.1D0/
      DATA ((GUNIT(I,J),I=1,3),J=0,1)
     F  /-1,0,0,-1,0,0/
      END
      SUBROUTINE SETUP0
      INCLUDE 'O8COMM.INC'
      ANALYT=.TRUE.
      EPSDIF=0.D0
      PROU=10
      MEU=20
      NRESET=4
      SILENT=.FALSE.
      RETURN
      END


