C*************************************************************
      SUBROUTINE O8MSG(NUM)
C WRITE MESSAGES ON "SPECIAL EVENTS"
      INCLUDE 'O8COMM.INC'
      INCLUDE 'O8QPDU.INC'
      INTEGER MDUALM,I
      PARAMETER (MDUALM=2*NRESM)
      INTEGER IPTR,IQTR,AITR(MDUALM)
      DOUBLE PRECISION SSTR,RIITR
      COMMON/O8QPTR/SSTR,RIITR,IPTR,IQTR,AITR
      INTEGER NUM
      SAVE
      IF ( NUM .LE. 0 .OR. NUM .GT. 25 ) RETURN
      GOTO (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,
     F    18,19,20,21,22,23,24,25) NUM
    1 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'RANKDEFICIENCY OF GRAD''S OF ACTIVE CONSTR.!'
      WRITE(MEU,*) 'ON THE BASIS OF DELMIN!'
      RETURN
    2 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'RESCALING OF OBJECTIVE FUNCTION SCF=',SCF
      RETURN
    3 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'RANKDEFICIENCY OF GRAD''S OF ACTIVE CONSTR.!'
      WRITE(MEU,*) ' DEL=',DEL
      RETURN
    4 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'RANKDEFICIENCY OF GRAD''S OF ACTIVE CONSTR.!'
      WRITE(MEU,*) ' DEL=',DEL
      RETURN
    5 CONTINUE
      WRITE(MEU,*) 'QPTERM<0: NO DIR. OF. DESC., TAUQP MAX'
      RETURN
    6 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'SECOND ORDER CORRECTION SUPPRESSED! '
      RETURN
    7 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'RETRY NEXT STEP WITH A=ID '
      RETURN
    8 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'SOME CONSTRAINT HAS GRADIENT EQUAL TO ZERO '
      WRITE(MEU,*) 'RESULTING D MAY BE NO DIRECTION OF DESCENT'
      RETURN
    9 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'TRY REGULARIZED SQP WITH INCREASED WEIGHTS'
      WRITE(MEU,*) 'SINCE DNORM SMALL OR INFEASIBILITY LARGE'
      RETURN
   10 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'QPSOLVER DID NOT COMPLETE, TRY D ANYWAY, MAY FAIL'
      RETURN
   11 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'DIRECT. DERIV. POSITIVE! MAY BE DUE TO INACCURATE'
      WRITE(MEU,*) 'GRADIENTS OR EXTREME ILLCONDITIONING'
      WRITE(MEU,*) 'DIRDER= ',DIRDER
      RETURN
   12 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'CALL OF MATDRU SUPPRESSED, MAT TOO LARGE'
      RETURN
   13 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'STARTVALUE CORRECTED IN ORDER TO FIT BOUNDS'
      RETURN
   14 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'TRY FULL SQP DUE TO SLOW PROGRESS IN X '
      RETURN
   15 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'TRY FULL SQP DUE TO SMALL STEPSIZES WHILE'
      WRITE(MEU,*) 'INFEASIBILITY LARGE'
      RETURN
   16 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'ON EXIT FROM O8QPDU DIR. DERIV. POSITIVE!'
      WRITE(MEU,*) 'TRY INCREASED TAUQP'
      RETURN
   17 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'TRY REGULARIZED SQP WITH INCREASED WEIGHTS'
      WRITE(MEU,*) 'NO DECREASE OF WEIGHTS POSSIBLE'
      WRITE(MEU,*) 'AND INCOMPATIBILITY LARGE'
      RETURN
   18 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'TRY REGULARIZED SQP WITH INCREASED WEIGHTS'
      WRITE(MEU,*) 'SINCE NO DIRECTION OF DESCENT HAS BEEN OBTAINED'
      RETURN
   19 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'DEGENERACY IN DUAL QP'
      WRITE(MEU,*) 'RESTR. ',IPTR,' TO BE ADDED'
      WRITE(MEU,*) 'NEW RII=',RIITR
      WRITE(MEU,*) 'LENGTH OF CURRENT WORKING SET=',IQTR
      WRITE(MEU,*) 'WORKING SET'
      WRITE(MEU,FMT='(15(I4,1X))') (AITR(I),I=1,IQTR)
      WRITE(MEU,*) 'PRIMAL FEASIBILITY VIOLATION IS=',SSTR
      RETURN
   20 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'DUAL QP SEEMINGLY INFEASIBLE '
      WRITE(MEU,*) 'THEORETICALLY IMPOSSIBLE'
      RETURN
   21 CONTINUE
      WRITE(MEU,*) 'STEP=',ITSTEP
      WRITE(MEU,*) 'NO UPDATE SINCE DG=0'
      RETURN
   22 CONTINUE
      WRITE(MEU,*) 'STEP',ITSTEP
      WRITE(MEU,*) 'FUNCTION EVALUATION RETURNS ERR=.TRUE.'
      RETURN
   23 CONTINUE
      WRITE(MEU,*) 'STEP',ITSTEP
      WRITE(MEU,*) 'CONTRAINT EVALUATION RETURNS ERR=.TRUE.'
      RETURN
   24 CONTINUE
      WRITE(MEU,*) 'STEP',ITSTEP
      WRITE(MEU,*) 'CURRENT POINT CANNOT BE CHANGED IN CURRENT'
      WRITE(MEU,*) 'DIRECTION DUE TO ERROR-MESSAGE FROM FUNCTION'
      WRITE(MEU,*) 'EVALUATION'
      RETURN
   25 CONTINUE
      WRITE(MEU,*) 'STEP',ITSTEP
      WRITE(MEU,*) 'REDUCE STEPSIZE DUE TO ERROR-INDICATOR SET'
      WRITE(MEU,*) 'BY USERS FUNCTION EVALUATION'
      RETURN
      END
