      DOUBLE PRECISION FUNCTION O8SC3(N,M,J,A,LDA,B)
C     MULTIPLY COLUMN J SECTION (N TO M) OF MATRIX A WITH VECTOR B
      IMPLICIT NONE
      INCLUDE 'O8CONS.INC'
      DOUBLE PRECISION A,B,S
      INTEGER N,M,I,J,LDA
      DIMENSION A(LDA,*),B(*)
      SAVE
      S=ZERO
      DO  I=N,M
        S=S+A(I,J)*B(I)
      ENDDO
      O8SC3=S
      RETURN
      END
