      SUBROUTINE SOLCHK
      INCLUDE 'O8COMM.INC'
      INCLUDE 'O8CONS.INC'
      INCLUDE 'USER2.INC'
C***** THE USER MAY ADD ADDITIONAL COMPUTATIONS USING THE COMPUTED
C      SOLUTION HERE
      RETURN
      END
