install:
	install --owner=root --group=root --mode=644 memoization.system $(DESTDIR)/usr/share/common-lisp/systems/
	cp -r Makefile  Load-Memoization.lisp  Memoization-Examples.lisp  Memoization.lisp  package.lisp  \
		Save-Memo-Table.lisp  \
		$(DESTDIR)/usr/share/common-lisp/repositories/memoization

