.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH REGISTER-COMMON-LISP-IMPLEMENTATION 1 "September 12, 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
register-common-lisp-implementation \- registers a Common Lisp Implementation
.SH SYNOPSIS
.B register-common-lisp-implementation
.RI compiler-name
.SH DESCRIPTION
.B register-common-lisp-implementation
is a program that registers the common lisp implementation
named by
.B compiler-name.
To this effect it requires that the implementation installed
a build-script named /usr/lib/common-lisp/bin/compiler-name.sh 
file.

.SH OPTIONS
None.
.SH SEE ALSO
.BR /usr/share/doc/common-lisp-controller/README.design,
.BR unregister-common-lisp-implementation (1),
.BR register-common-lisp-source (1),
.BR unregister-common-lisp-source (1).
.br
.SH AUTHOR
This manual page was written by Peter Van Eynde <pvaneynd@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
