.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "REGISTER-COMMON-LISP-SOURCE" "1" ""
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
unregister-common-lisp-source \- unregisters a Common Lisp source package
.SH SYNOPSIS
.B unregister-common-lisp-source
.RI package-name
.SH DESCRIPTION
.B unregister-common-lisp-source
is a program that unregisters the common lisp source package
named by
.B package-name.
To this effect it requires that the source installed
a system-file named /usr/share/common-lisp/systems/package-name.asd
file.

.SH OPTIONS
None.
.SH SEE ALSO
.BR /usr/share/doc/common-lisp-controller/README.design,
.BR register-common-lisp-source (1),
.BR unregister-common-lisp-implementation (1),
.BR register-common-lisp-implementation (1).
.br
.SH AUTHOR
This manual page was written by Peter Van Eynde <pvaneynd@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
