#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# autobuild?
db_input high common-lisp-controller/auto-build || true
db_go

#show note..
db_input high  common-lisp-controller/how-to-control || true
db_go


