.\" 	-*- Mode: Nroff -*-
.TH "clc-autobuild-source" "8" "" "" ""

.SH "NAME"
clc-autobuild-library \- Sets autobuild status for a Common Lisp library

.SH "SYNOPSIS"
.B clc-autobuild-library library value [OPTIONS]

.SH "DESCRIPTION"
This command sets the autobuild status for a Common Lisp
library package. The valid autobuild values are "yes", "no", and "inherit".
When the autobuild valus is "inherit", then the library package inherits
the default autobuild value for each implementation.

This command also accepts these "virtual" implementation names
.BR
  cmucl    (equivalent to "cmucl-normal cmucl-safe cmucl-safe")
.BR
  allegro  (equivalent to "acl alisp alisp8 mlisp mlisp8")

.SH "OPTIONS"
.TP 16
.B \-h
Print short help message

.SH "BUGS"

Bug reports should be sent to the debian BTS, preferably with
reportbug.

.SH "AUTHOR"
Kevin M. Rosenberg <kmr@debian.org>, Sep 2002
