.\" 	-*- Mode: Nroff -*-
.TH "clc-not-compatible" "8" "" "" ""

.SH "NAME"
clc-not-compatible \- Sets autobuilding based on Common Lisp source ompatibility

.SH "SYNOPSIS"
.B clc-not-compatible source-pkg-name [impl ...] [OPTIONS]

.SH "DESCRIPTION"
This command sets compatibility for a Common Lisp source package.
This function will set the package's autobuild to "no" for
all implementations supplied on the command line.
.PP
This command also accepts these "virtual" implementation names
.BR
  cmucl    (equivalent to "cmucl-normal cmucl-safe cmucl-safe")
.BR
  allegro  (equivalent to "acl alisp alisp8 mlisp mlisp8")

.SH "OPTIONS"
.TP 16
.B \-h
Print short help message

.SH "BUGS"

Bug reports should be sent to the debian BTS, preferably with
reportbug.

.SH "AUTHOR"
Kevin M. Rosenberg <kmr@debian.org>, Sep 2002
