#!/bin/sh

set -e

progname=$(basename $0)

if [ ! -d "$HOME" ]; then
  echo "User home directory $HOME does not exist as a directory" >&2
  exit 3
fi

clc_user_dir=$HOME/.clc

if [ ! -d "$clc_user_dir" ]; then
  echo "User CLC directory $clc_user_dir does not exist."
  echo "Maybe you never registered any user packages."
  exit 3
fi

clc_user_db=$HOME/.clc/user-packages.db

if [ ! -f "$clc_user_db" ]; then
  "No user packages are currently registered."
  exit 0
fi

if [ -z "$1" ] ; then
 cat <<EOF
usage: $progname package-asdf-file
Registers a Common Lisp package to the Common Lisp Controller system.
EOF
    exit 1
fi

asdf_file=$(realpath "$1" 2>/dev/null || true)

if [ -f "$asdf_file" ]; then
    found=$(grep "^${asdf_file}\$" $clc_user_db || true)
    if [ "$found" ]; then
	grep -v "^${asdf_file}\$" $clc_user_db > ${clc_user_db}.new || true
	mv ${clc_user_db}.new $clc_user_db
	echo "User package $asdf_file unregistered."
    else
	echo "User package $asdf_file was not registered."
    fi
else
    echo "User package file $1 not found on file system."
fi

