#!/bin/bash

# first check if there is at least a compiler-name:

if [ -z "$1"  ] ; then
 cat <<EOF
$0 compiler-name 

registers a Common Lisp compiler to the 
Common-Lisp-Controller system.
EOF
    exit 1
fi

FILE="/usr/lib/common-lisp/bin/$1.sh"

if [ ! -f "$FILE" ] ; then
  cat <<EOF
$0: I cannot find the script $FILE for the implementation $1
EOF
  exit 2
fi

if [ ! -r "$FILE" ] ; then
  cat <<EOF
$0: I cannot read the script $FILE for the implementation $1
EOF
  exit 2
fi

#install the defsystem into the lisp

sh "$FILE" install-defsystem || (echo Installation defsystem failed ; exit 3) 

# now recompile the stuff
for i  in /usr/share/common-lisp/systems/*.system  ; do
    if [ -f $i -a -r $i ] ; then
     i=${i%.system}
     package=${i##*/}
     if [ -f /etc/common-lisp/autobuild -o \
          -f "/etc/common-lisp/$1/autobuild" -o \
          -f "/etc/common-lisp/$1/$package/autobuild" ] ; then
       echo recompiling package $package for implementation $1
       /usr/bin/clc-send-command --quiet recompile $package $1
     fi
    fi
done


cat <<EOF
$0: Compiler $1 installed
EOF
