#!/bin/bash

if [ `id -u` != 0 ] ; then
 echo You need to be root to run $0
 exit 1
fi

# first check if there is at least a package-name:

if [ -z "$1" ] ; then
 cat <<EOF
$0 package-name

unregisters a Common Lisp source tree to the 
Common-Lisp-Controller system.
EOF
    exit 1
fi

FILE="/usr/share/common-lisp/systems/$1.system"
SOURCENAME="/usr/share/common-lisp/source/$1"
if [ ! \( -d "$SOURCENAME" -o  -h "$SOURCENAME" \) ] ; then 
    cat <<EOF
$0: symlink $SOURCENAME does not exist.

This is where I expected package $1 to be.

Maybe you already uninstalled it?
EOF
    exit 0
fi

if [ ! -e "$FILE" -a ! -h "$FILE" ] ; then                                                                                                                   
    cat <<EOF
$0: $FILE does not exist.  This is needed to  
unregister the $1 package.

Maybe you already uninstalled it?
EOF
    exit 0
fi

for compiler in /usr/lib/common-lisp/bin/*.sh ; do
    if [ -f $compiler -a -r $compiler ] ; then
     i=${compiler##*/}
     i=${i%.sh}
     /usr/bin/clc-send-command --quiet remove $1 $i
    fi
done

cat <<EOF
$0: Package $1 uninstalled
EOF
