!.\" 	-*- Mode: Nroff -*-
.TH "clc-register-user-package" "1" "" "" ""

.SH "NAME"
clc-register-user-package \- Register a Common Lisp user package

.SH "SYNOPSIS"
.B clc-register-user-package <asdf-file>

.SH "DESCRIPTION"
This command registers a user package. It is given the filename of the ASDF file
for the user package. When registered, a user package is loaded in preference to 
any system-wide installation of the same system name.

.SH "FILES"
The user package database is stored in ~/.clc/user-packages.db

.SH "BUGS"

Bug reports should be sent to the debian BTS, preferably with
reportbug.

.SH "AUTHOR"
Kevin M. Rosenberg <kmr@debian.org>, Oct 2002
